### ISSUE TITLE
About Testing

### ISSUE THREAD

**Issue by a673660099** [MCG-NJU/CamLiFlow#1]
Please：
Your article is great！！！
But I want to test my datasets about optical flow , so what should I do next? I only see the evaluation，No having demo or test module to support my test.
Hope to get a reply

**Comment by afterthat97** [comment]
Sorry for the inconvenience, we will provide a demo in the future.

**Comment by a673660099** [comment]
> Sorry for the inconvenience, we will provide a demo in the future.

cao！ That's Great!

**Comment by afterthat97** [comment]
The demo is available now, please check the latest commit.

**Comment by a673660099** [comment]
> The demo is available now, please check the latest commit.
Hello, after reading the demo, having a question ,that is it necessary to test whether any picture must have disparity input and RGB input
