### ISSUE TITLE
About PointConvDW

### ISSUE THREAD

**Issue by DQiaole** [MCG-NJU/CamLiFlow#11]
Hi~
Thanks for your great works. I was very curious about the PointConvDW used in the CamLiRAFT, why did the standard PointConv be used in the Encoder3D, while later PointConvDW was used in FlowHead3D, GRU3D, and MotionEncoder3D? Is there a specific reason?

**Comment by afterthat97** [comment]
1. PointConvDW is a depth-wise version of PointConv (inspired by depth-wise convolution), and runs much faster than PointConv.
2. Replacing PointConv with PointConvDW in the **encoder** can hurt the performance severely, thus we keep the standard design. For other positions (such as FlowHead3D, GRU3D, and MotionEncoder3D), the performance remains the same or even better.
