### ISSUE TITLE
Implementing details in CamLiRAFT

### ISSUE THREAD

**Issue by ZhangYushan3** [MCG-NJU/CamLiFlow#12]
Hi, thanks for the great work!
I wonder how did you get the numbers in Table 2 and Table 5 in CamLiRAFT?
From my understanding, Table 2 is trained on dataset using lifting preprocess from FlowNet3D, training/testing split is 19640/3824. All points including the occluded ones are evaluated for 3D metrics.
Table 2 left part is trained on dataset using lifting preprocess from HPLFlowNet, right part is trained on dataset using lifting preprocess from FlowNet3D, training/testing split is 19640/3824. Only non-occluded points are evaluated for 3D metrics.
Is that correct? How did you get these numbers? Did you train it by yourself? Are these numbers the final version or will it change since it's currently an arxiv version.

**Comment by afterthat97** [comment]
Evaluation details:

* Table 2: all points including the occluded ones are evaluated for 3D metrics. The testing set is preprocessed by our script.
* Table 5 (left part): we use the official code of [HPLFlowNet](https://github.com/laoreja/HPLFlowNet/blob/master/data_preprocess/process_flyingthings3d_subset.py) to preprocess the testing set; occluded points are removed during training and testing.
* Table 5 (right part): we follow [FlowNet3D](https://github.com/xingyul/flownet3d) and download the preprocessed data from [here](https://drive.google.com/file/d/1CMaxdt-Tg1Wct8v8eGNwuT7qRSIyJPY-/view?usp=sharing). Occluded points
are present at the input of the networks but are not taken into account to compute the metrics.

For table 5, the results of other methods are reported from [OGSF-Net](https://github.com/BillOuyang/OGSFNet). For table 2, the underlined results are reported from OFSG-Net, while other results are evaluated using the official weights by myself.

We will release the pretrained weight and training script of CamLiRAFT-L and CamLiPWC-L soon.

**Comment by ZhangYushan3** [comment]
Hi, what is the difference between your preprocessing script and the flownet3d proprecessing?--发自新浪邮箱客户端
在 4月3日 07:41，Haisong Liu ***@***.***> 写道：

Evaluation details:

Table 2: all points including the occluded ones are evaluated for 3D metrics. The testing set is preprocessed by our script.
Table 5 (left part): we use the official code of HPLFlowNet to preprocess the testing set; occluded points are removed during training and testing.
Table 5 (right part): we follow FlowNet3D and download the preprocessed data from here. Occluded points

are present at the input of the networks but are not taken into account to compute the metrics.

For table 5, the results of other methods are reported from OGSF-Net. For table 2, the underlined results are reported from OFSG-Net, while other results are evaluated using the official weights by myself.
We will release the pretrained weight and training script of CamLiRAFT-L and CamLiPWC-L soon.

&mdash;

**Comment by afterthat97** [comment]
The only difference is that we use the subset of FlyingThings3D (19640/3824), while FlowNet3D uses the full FlyingThings3D and manually excludes many samples (remaining ~2000). In practice, the distribution of them is close (e.g., for FlowNet3D, EPE3d (full): 0.212 vs. 0.214). Thus, our testing set is almost the same with the one of FlowNet3D.

**Comment by ZhangYushan3** [comment]
Thanks, crystal clear :)
