### ISSUE TITLE
Question about the implementation of the ablation in the first row of table 8 in your pami version

### ISSUE THREAD

**Issue by pkqbajng** [MCG-NJU/CamLiFlow#13]
Hi,
  Thanks for your excellent work. In the table 8 of the pami version, you mentioned that the naive implementation is directly projecting 3D features on to image plane with empty locations filled by zeros. But I don't find the corresponding code in this project, could you please explain more about the details? For example, the coordinates will be decimal and is hard to process in the lower levels.

**Comment by pkqbajng** [comment]
Thank you for your quickly response, I understand it, best wishes to your following research

**Comment by afterthat97** [comment]
Thanks!
