### ISSUE TITLE
About perspect2parallel and parallel2perspect

### ISSUE THREAD

**Issue by YangHan-Morningstar** [MCG-NJU/CamLiFlow#6]
Hi there, thanks for your excellent work!
When I debug, I'm confused about the functions perspect2parallel and parallel2perspect, could your tell me what do these two functions do or which part of the paper do they correspond to? Thanks a lot!

**Comment by afterthat97** [comment]
Please refer to section "3.3. Inverse Depth Scaling" in our paper.

**Comment by YangHan-Morningstar** [comment]
Got it! Thanks!
