### ISSUE TITLE
Whether camera intrinsic parameters are required？

### ISSUE THREAD

**Issue by Ouya-Bytes** [MCG-NJU/CamLiFlow#8]
Whether must  that get the camera intrinsic parameters in the stage of inference？
In practice，Can i use the depth estimate method get image depth replace the points cloud depth from camera intrinsic params?
Looking forward to your reply， thanks!

**Comment by afterthat97** [comment]
Sure, you can.

**Comment by Ouya-Bytes** [comment]
thanks for your reply.
