### ISSUE TITLE
work on Quadro RTX 6000

### ISSUE THREAD

**Issue by 2020namemyself2020** [MCG-NJU/CamLiFlow#9]
Thanks for your great work! The code didn‘t work on that platform because of the correlation module in /model/csrc/correlation2d. 
##################################
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by afterthat97** [comment]
Since RTX A6000 belongs to the 30-series, CUDA 11 is required:

```
conda install pytorch==1.10.1 torchvision cudatoolkit=11.3 -c pytorch
```

**Comment by 2020namemyself2020** [comment]
Thanks for your help. It does work！

**Comment by afterthat97** [comment]
Good luck!
